# This script collects the data generated by aihwkit and puts all the results in a csv file
# The input directory must contain RPU_Config.txt, Summary.dat, and metrics.csv files for each simulation

import argparse
import data_utils as du

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=str, help="Path to the directory containing aihwkit/pytorch files")
    parser.add_argument("output", type=str, help="Path to the output file")

    args = parser.parse_args()

    df = du.get_pytorch_df(args.input)

    df.to_csv(args.output, index=False)